export const API_DASHBOARD_CHECKIN_DATA_SUCCESS = "API_DASHBOARD_CHECKIN_DATA_SUCCESS";
export const API_DASHBOARD_CHECKIN_DATA_FAILURE = "API_DASHBOARD_CHECKIN_DATA_FAILURE";
export const API_DASHBOARD_GET_CHECKIN_DATA = "API_DASHBOARD_GET_CHECKIN_DATA"

export const API_DASHBOARD_BREAKS_DATA_SUCCESS = "API_DASHBOARD_BREAKS_DATA_SUCCESS"
export const API_DASHBOARD_BREAKS_DATA_FAILURE = "API_DASHBOARD_BREAKS_DATA_FAILURE"
export const API_DASHBOARD_BREAKS_DATA = "API_DASHBOARD_BREAKS_DATA"