export const UPDATE_TECHNOLOGY_REQUEST = " UPDATE_TECHNOLOGY_REQUEST,"
export const UPDATE_TECHNOLOGY_SUCCESS = "  UPDATE_TECHNOLOGY_SUCCESS,"
export const UPDATE_TECHNOLOGY_FAILURE = "  UPDATE_TECHNOLOGY_FAILURE,"
